### ISSUE TITLE
repo checker approves broken builds

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1712]
https://build.suse.de/request/show/172868 shouldn't have been approved, but it was. Please debug

**Comment by jberry-suse** [comment]
As of rework for handling generic repositories the repo_checker no longer blocks on failed package builds. A couple reasons being the desire to have it skip _certain_ failed packages like module check for SLE the others being that build failures are checked by staging tools and are not specifically repo_checker related. Obviously, the down side is in the way the reviews are tied to requests instead of stagings. This has been discussed previously and would make more sense tied to staging project (#1038), but that was something left for later since I had hoped this would all migrate to a proper CI setup. Obviously, multiple ways to implement this at a project level and could abuse psuedo meta.

Blocking on build failures is cumbersome for generic project review since build failures may be expected in certain circumstances like target project or devel project. Can re-instate the staging failure check with exceptions for the 000 prefix packages as a band-aid, but really tying to project/repository is the proper solution.

One could stage a request in a staging where it passed review then move it to another where it is missing deps and then merge the whole set. Tying such group level reviews to requests was never the proper abstraction.

**Comment by coolo** [comment]
If the package didn't even build, how on earth did repo checker check its dependencies? And why are you giving me lectures instead of fixing the bug?

**Comment by coolo** [comment]
Sorry about the lectures part - but I still don't understand how you can explain one bug away by saying the whole concept is broken, when it worked quite reliably for many years.

**Comment by lnussel** [comment]
Jimmy Berry schrieb:
> As of rework for handling generic repositories the repo_checker no
> longer blocks on failed package builds. A couple reasons being the
> desire to have it skip _certain_ failed packages like module check for
> SLE the others being that build failures are checked by staging tools
> and are not specifically repo_checker related. Obviously, the down
> side is in the way the reviews are tied to requests instead of
> stagings. This has been discussed previously and would make more sense
> tied to staging project (#1038), but that was something left for later
> since I had hoped this would all migrate to a proper CI setup.
> Obviously, multiple ways to implement this at a project level and
> could abuse psuedo meta.

IIUC the in the works OBS status checks API is meant to provide
something like per repo results to replace per request reviews for use
cases like openQA and repo checker.

> Blocking on build failures is cumbersome for generic project review
> since build failures may be expected in certain circumstances like
> target project or devel project. Can re-instate the staging failure
> check with exceptions for the 000 prefix packages as a band-aid, but

Yes, please. We need that back ASAP to avoid repo checker letting
failures pass through.

> One could stage a request in a staging where it passed review then
> move it to another where it is missing deps and then merge the whole
> set. Tying such group level reviews to requests was never the proper
> abstraction.

Yes, known gap that sucks and should be fixed but no reason to add even
more holes to the process :-)

**Comment by jberry-suse** [comment]
> IIUC the in the works OBS status checks API is meant to provide something like per repo results to replace per request reviews for use cases like openQA and repo checker.

And has been discussed that this does not resolve the problem.

> Yes, please. We need that back ASAP to avoid repo checker letting failures pass through.

Sure, but this just reduce the chance of a certain flow while adding additional complexity.

> Yes, known gap that sucks and should be fixed but no reason to add even more holes to the process :-)

That's one way to look at it, but really it's a much larger problem.

**Comment by jberry-suse** [comment]
> Sorry about the lectures part - but I still don't understand how you can explain one bug away by saying the whole concept is broken, when it worked quite reliably for many years.

When you say years I assume you mean the previous repo-checker that only ran against Factory. That checked binaries in devel projects and thus completely ignored staging projects and thus would miss anything (including build failures) that occurred there. Also suffered the same problem of once a review was accepted it is never checked again.

I would love to fix the problem and proposed the real solution instead of continuing the endless flow of workarounds. Unfortunately, everyone looked at the lowest hanging fruit as if that solved something and ignored the rest. Also never had the follow-up discussions about the details as this and other problem demonstrate the fundamental needs for a lower-level change.

I simply had the false expectation that people would see the big picture and the point and we'd make some real progress. Instead we're back to suddenly urgent problems that have been problems for a long time.

**Comment by jberry-suse** [comment]
So what we can do is introduce some reduction techniques like the build failures check I originally had in place using the staging API and perhaps break more scopes by having the staging tools re-add the repo-checker review when making changes (as the currently don't touch it).

Originally, my design was to wait until the target project finished building as well. That way repo-checker waits until everything has completely settled, but then was told it doesn't provide feedback soon enough. So I relaxed that, then similarly the build failures are really not related to repo-checker's job.

> If the package didn't even build, how on earth did repo checker check its dependencies?

That's another question for OBS, as it provides the previously built binaries as if they represent the current repository state. Obviously they do not. If they were replaced with nothing then likely other errors would be seen by repo-checker.

So we are back to doing OBS's job for it in endless extra layers of code.

**Comment by jberry-suse** [comment]
> And why are you giving me lectures instead of fixing the bug?

To be clear, I'd love to fix "the bug", but this doesn't just happens to wait and thus avoid one of the cases of the bug....not the actual bug.

**Comment by jberry-suse** [comment]
It's like writing a parser that specifically tries to handle every possible broken input instead of generically handling the correct input. Yeah, we can fix the case we ran into today by adding another logic branch, but that is not even close to the solution. Done at the scale of all these tools and it's rather endless.

**Comment by jberry-suse** [comment]
As an aside, one can see the [number of problems slipping through prior to repo-checker rewrite](https://metrics.opensuse.org/d/osrt_dashboard/osrt-dashboard?panelId=4&fullscreen&orgId=1&from=1411875729924&to=1492153329924) via the various avenues.
